In [ ]:
What is Numpy?
* Numpy means Numerical Python.
* Open Source
* Numerical Computing / Scientific Computing Library
* N-dimensional array objects
* It work with scientific Computing, Data Analysis and Machine Learning etc.
* Mathematical Functions (Linear algebra, Fourier transformation, Statistical function, broadcasting and random number generation)


In [ ]:
Numpy Environment Setup ---->
Open a CMD or PowerShell window on your computer.
pip install numpy

verify numpy -
import numpy

In [25]:
#importing library
#np is alias
import numpy as np 

#ar1 is the ndarray object
ar1=np.array([1,2,3,4,5,6])
print(arr1)

[1 2 3 4 5 6]


In [26]:
#2x2 martix using numpy 
#Two-dimensional array
ar2=np.array([[1,2,3],[4,5,6]])
print(ar2)

[[1 2 3]
 [4 5 6]]
